### ISSUE TITLE
Flake8 wrapper doesn't annotate all errors

### ISSUE THREAD

**Issue by FirefoxMetzger** [liskin/gh-problem-matcher-wrap#2] opened 2021-03-27 08:36 UTC
First of all, great action! Not only does it work, but it also taught me about problem matchers. Super useful 🚀 

The action does create annotations as advertised; however, it seems to miss some of them for the flake8 linter. Flake8 finds a total of 16 issues, but only 10 of them are annotated. The following lines are missed by the matcher:

The code line `## An added line that breaks the linter` I've added specifically to test this produces

```
.\imageio\core\functions.py:620:1: E266 too many leading '#' for block comment
```

as expected, but is not annotated.

Some errors in files not touched by a PR are found in the action, but also not annotated (this is a beta feature on GH, so I guess it may be unrelated to this repo). Examples

```
.\imageio\core\format.py:638:13: E731 do not assign a lambda expression, use a def
.\imageio\core\util.py:19:1: E402 module level import not at top of file
.\imageio\core\util.py:186:1: E402 module level import not at top of file
.\imageio\core\util.py:226:9: E731 do not assign a lambda expression, use a def
```

Here is an example commit from the repo where I've set things up:
https://github.com/imageio/imageio/pull/614/commits/38b2d86654fa3b8cce879e21c9fe842d45f1881c

And here is the accompanying Action log: 
https://github.com/imageio/imageio/runs/2207580247?check_suite_focus=true

**Comment by FirefoxMetzger** [comment] 2021-03-27 08:41
The flake8 regex does find all the lines in question; where else could it fail?

**Comment by FirefoxMetzger** [comment] 2021-03-27 10:16
Working my way through the issues and resolving all but my test error made the annotation for it appear as desired.

Is there a limitation regarding the number of annotations? (10 reports seems suspicious) If so, is it possible to raise it?

**Comment by liskin** [comment] 2021-03-27 14:28
> Is there a limitation regarding the number of annotations? (10 reports seems suspicious) If so, is it possible to raise it?

It seems there is:

* https://github.community/t/annotation-limitation/17998/2
* https://github.community/t/maximum-number-of-annotations-that-can-be-created-using-github-actions-logging-commands/16991/3

And I don't think there's anything I can do about that. :-(

**Comment by FirefoxMetzger** [comment] 2021-03-27 16:39
Bummer. Do you think it could be worthwhile to add this limitation to the Readme (together with the links you shared)?

Two other changes that came to mind (not sure if feasable):

1. New Feature: Arguably, errors on lines that were touched by the PR are more important than errors on lines that are not related to the PR. Is it possible to sort errors based on that and display the ones related to the PR first?
2. Since it is possible to have 10 annotations per step, one option is to split linting into multiple steps (e.g. by folder). This is nothing the action can do, but perhaps adding a note/suggestion about this in the readme might be educational.

**Comment by liskin** [comment] 2021-03-27 17:02
Yeah, it'd probably make sense to mention this limitation somewhere, including the workaround of manually splitting these.

> New Feature: Arguably, errors on lines that were touched by the PR are more important than errors on lines that are not related to the PR. Is it possible to sort errors based on that and display the ones related to the PR first?

If the errors on lines "unrelated" to the PR were introduced by the PR, they are as relevant as any other. If they were there before the PR, then yeah, they're less relevant, but in that case you're probably doing CI/CD wrong: master/main should be green at all times. If there are tests failing, the PR that introduced that should never have been merged. Although yeah, I can understand that in a "move fast break things" model, unrelated failing tests do happen. In that case, however, you might need a more advanced CI/CD system that can actually track when a test started failing and what the cause was, like Jenkins. GitHub Actions doesn't do any such advanced stuff, yet, and maybe never will.

Anyway, none of this is really related to what this Action does, though. We can update the docs (PRs and/or donations welcome), but the rest should probably be brought up at https://github.community/ rather than here.

**Closed as completed** 2021-03-27 21:33 UTC
